### ISSUE TITLE
Update for Julia 1.1 and 1.2

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#299]
- [x] IncrementalInference (JuliaRobotics/IncrementalInference.jl#255)
- [x] RoME (JuliaRobotics/RoME.jl#172)
- [x] Caesar (JuliaRobotics/Caesar.jl#323)
- [x] ApproxManifoldProducts (JuliaRobotics/ApproxManifoldProducts.jl#16)
- [x] KernelDensityEstimate (JuliaRobotics/KernelDensityEstimate.jl#44)
- [ ] Arena
- [x] KernelDensityEstimatePlotting (JuliaRobotics/KernelDensityEstimatePlotting.jl#10)
- [x] RoMEPlotting (JuliaRobotics/RoMEPlotting.jl#42)

**Comment by dehann** [comment]
doing Arena separately
